// ═══════════════════════════════════════════════════════════════
// Firmware Header Template — Algo_${ID}.h
// ═══════════════════════════════════════════════════════════════
// Generated by OpenPulse Algorithm Builder
// Place at: firmware/src/algorithms/${LAYER}/Algo_${ID}.h
//   where ${LAYER} = base | fusion (cross-sensor and composite)
// ═══════════════════════════════════════════════════════════════

#pragma once

#include "../../framework/AlgorithmBase.h"
#include "../../framework/RingBuffer.h"
#include "../../framework/Channels.h"

// Include dependency algorithm headers (if this algorithm consumes others)
// #include "Algo_${DEP_ID}.h"

class Algo_${ID} : public AlgorithmBase {
public:
    // ─── AlgorithmBase interface ─────────────────────────
    void init() override;
    void update(uint32_t now_ms) override;
    AlgorithmOutput getOutput() const override;
    AlgoState getState() const override;

    const char* getID() const override { return "${ID}"; }
    const char* getName() const override { return "${NAME}"; }
    const char* getUnit() const override { return "${UNIT}"; }

    AlgoClassification getClassification() const override {
        return AlgoClassification::${CLASSIFICATION};
        // WELLNESS | HEALTH_INDICATOR | HEALTH_SCREENING | SPORT_PERFORMANCE
    }
    AlgoTier getTier() const override {
        return AlgoTier::${TIER};
        // REALTIME | PERIODIC | ON_DEMAND | OFF_DEVICE
    }
    uint16_t ramUsage() const override { return sizeof(*this); }

    // ─── Algorithm-specific public API ───────────────────
    // Add any methods other algorithms need to consume this output
    // float getSubMetric() const;

private:
    AlgoState state_ = AlgoState::IDLE;

    // ─── Ring Buffers ────────────────────────────────────
    // Sized from spec: N = window_seconds × sample_rate
    RingBuffer<float, ${BUFFER_SIZE}> ${PRIMARY_BUFFER};
    // RingBuffer<float, ${ACCEL_BUFFER_SIZE}> accel_buffer_;  // for motion rejection

    // ─── Filter State ────────────────────────────────────
    // IIR filter state variables (SOS sections)
    // float sos_state_[${SOS_SECTIONS}][2] = {};

    // ─── Algorithm State ─────────────────────────────────
    // ${ALGORITHM_SPECIFIC_STATE}
    // e.g., peak detector state, running averages, counters

    // ─── Output Cache ────────────────────────────────────
    AlgorithmOutput output_ = {0, 0, 0, false};
    // For CalibratedOutput:
    // CalibratedOutput calibrated_output_ = {0, 0, 0, 0, 0, false, false, 0};

    // ─── Internal Methods ────────────────────────────────
    float computeSQI() const;
    // float computeMotionLevel(uint32_t now_ms);  // If PPG/ECG-based
    // float applyFilter(float sample);             // IIR filter step
};
