#!/usr/bin/env python3
"""
OpenPulse Filter Designer
─────────────────────────
Generates IIR filter coefficients for use in firmware algorithms.
Outputs copy-pasteable C++ arrays.

Usage:
    python3 filter_designer.py                 # Interactive mode
    python3 filter_designer.py --preset ppg    # PPG bandpass preset
    python3 filter_designer.py --preset ecg    # ECG bandpass preset
    python3 filter_designer.py --preset resp   # Respiratory bandpass preset

Requirements:
    pip3 install scipy numpy
"""

import argparse
import sys

try:
    import numpy as np
    from scipy.signal import butter, sosfreqz, sosfilt, iirnotch
    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False


# ─── Presets ────────────────────────────────────────────────────

PRESETS = {
    "ppg": {
        "name": "PPG Heart Rate Bandpass",
        "order": 4,
        "low": 0.5,
        "high": 4.0,
        "fs": 100,
        "btype": "band",
        "citation": "Elgendi 2013, Covers 30-240 BPM",
    },
    "ecg": {
        "name": "ECG QRS Detection Bandpass",
        "order": 4,
        "low": 5.0,
        "high": 15.0,
        "fs": 200,
        "btype": "band",
        "citation": "Pan-Tompkins 1985, QRS complex 5-15 Hz",
    },
    "resp": {
        "name": "Respiratory Rate from PPG",
        "order": 2,
        "low": 0.1,
        "high": 0.5,
        "fs": 100,
        "btype": "band",
        "citation": "Respiratory sinus arrhythmia, 6-30 breaths/min",
    },
    "eda_lp": {
        "name": "EDA Low-Pass (Tonic)",
        "order": 2,
        "low": 0.05,
        "high": None,
        "fs": 10,
        "btype": "low",
        "citation": "Tonic EDA component < 0.05 Hz",
    },
    "eda_hp": {
        "name": "EDA High-Pass (Phasic)",
        "order": 2,
        "low": 0.05,
        "high": None,
        "fs": 10,
        "btype": "high",
        "citation": "Phasic EDA component > 0.05 Hz",
    },
    "ppg_dc": {
        "name": "PPG DC Removal (High-Pass)",
        "order": 2,
        "low": 0.5,
        "high": None,
        "fs": 100,
        "btype": "high",
        "citation": "Remove baseline wander from PPG",
    },
    "step": {
        "name": "Step Detection Bandpass",
        "order": 2,
        "low": 0.5,
        "high": 3.0,
        "fs": 50,
        "btype": "band",
        "citation": "Walking/running 30-180 steps/min",
    },
}


def design_filter(order, low, high, fs, btype):
    """Design a Butterworth filter and return SOS coefficients."""
    if btype == "band":
        sos = butter(order, [low, high], btype="band", fs=fs, output="sos")
    elif btype == "low":
        sos = butter(order, low, btype="low", fs=fs, output="sos")
    elif btype == "high":
        sos = butter(order, low, btype="high", fs=fs, output="sos")
    return sos


def sos_to_cpp(sos, name, citation, fs, low, high, btype, order):
    """Convert SOS matrix to C++ code."""
    n_sections = sos.shape[0]

    lines = []
    lines.append(f"// {name}")
    lines.append(f"// {order}th-order Butterworth {btype}pass")
    if btype == "band":
        lines.append(f"// Cutoff: {low}–{high} Hz at {fs} Hz sample rate")
    elif btype == "low":
        lines.append(f"// Cutoff: {low} Hz low-pass at {fs} Hz sample rate")
    elif btype == "high":
        lines.append(f"// Cutoff: {low} Hz high-pass at {fs} Hz sample rate")
    lines.append(f"// Citation: {citation}")
    lines.append(f"// Generated by tools/filter_designer.py")
    lines.append(f"//")
    lines.append(f"// SOS format: each section has [b0, b1, b2, a0, a1, a2]")
    lines.append(f"// a0 is always 1.0 (normalized)")
    lines.append(f"")
    lines.append(f"constexpr int FILTER_{name.upper().replace(' ', '_').replace('-', '_')}_SECTIONS = {n_sections};")
    lines.append(f"")
    lines.append(f"// Second-Order Sections [b0, b1, b2, 1.0, a1, a2]")
    lines.append(f"const float FILTER_{name.upper().replace(' ', '_').replace('-', '_')}_SOS[{n_sections}][6] = {{")

    for i, section in enumerate(sos):
        b0, b1, b2, a0, a1, a2 = section
        comma = "," if i < n_sections - 1 else ""
        lines.append(f"    {{ {b0: .10e}f, {b1: .10e}f, {b2: .10e}f, {a0: .10e}f, {a1: .10e}f, {a2: .10e}f }}{comma}")

    lines.append("};")

    # Also generate a simple SOS filter function
    lines.append("")
    lines.append("// Apply filter to a single sample (call once per sample)")
    lines.append("// state[] must be zeroed on init, size = SECTIONS * 2")
    lines.append(f"inline float apply_filter_{name.lower().replace(' ', '_').replace('-', '_')}(")
    lines.append(f"    float input,")
    lines.append(f"    float state[{n_sections} * 2]")
    lines.append(f") {{")
    lines.append(f"    float x = input;")
    lines.append(f"    for (int s = 0; s < {n_sections}; s++) {{")
    lines.append(f"        const float* c = FILTER_{name.upper().replace(' ', '_').replace('-', '_')}_SOS[s];")
    lines.append(f"        float w = x - c[4] * state[s*2] - c[5] * state[s*2+1];")
    lines.append(f"        float y = c[0] * w + c[1] * state[s*2] + c[2] * state[s*2+1];")
    lines.append(f"        state[s*2+1] = state[s*2];")
    lines.append(f"        state[s*2] = w;")
    lines.append(f"        x = y;")
    lines.append(f"    }}")
    lines.append(f"    return x;")
    lines.append(f"}}")

    return "\n".join(lines)


def main():
    if not HAS_SCIPY:
        print("ERROR: scipy and numpy are required.")
        print("Install with: pip3 install scipy numpy")
        sys.exit(1)

    parser = argparse.ArgumentParser(description="OpenPulse Filter Designer")
    parser.add_argument("--preset", choices=list(PRESETS.keys()),
                        help="Use a preset filter configuration")
    parser.add_argument("--all", action="store_true",
                        help="Generate all presets")
    parser.add_argument("--output", "-o", type=str, default=None,
                        help="Output file (default: stdout)")
    args = parser.parse_args()

    results = []

    if args.all:
        for key, preset in PRESETS.items():
            sos = design_filter(
                preset["order"], preset["low"], preset["high"],
                preset["fs"], preset["btype"]
            )
            cpp = sos_to_cpp(
                sos, key, preset["citation"],
                preset["fs"], preset["low"], preset["high"],
                preset["btype"], preset["order"]
            )
            results.append(cpp)
    elif args.preset:
        preset = PRESETS[args.preset]
        sos = design_filter(
            preset["order"], preset["low"], preset["high"],
            preset["fs"], preset["btype"]
        )
        cpp = sos_to_cpp(
            sos, args.preset, preset["citation"],
            preset["fs"], preset["low"], preset["high"],
            preset["btype"], preset["order"]
        )
        results.append(cpp)
    else:
        print("Available presets:")
        for key, preset in PRESETS.items():
            print(f"  {key:12s}  {preset['name']}")
        print()
        print("Usage:")
        print("  python3 filter_designer.py --preset ppg")
        print("  python3 filter_designer.py --all")
        print("  python3 filter_designer.py --all -o firmware/src/framework/filters.h")
        return

    output = "\n\n".join(results)

    header = """#pragma once
// ═══════════════════════════════════════════════════════════════
// OpenPulse — Pre-computed IIR Filter Coefficients
// Generated by tools/filter_designer.py
//
// DO NOT EDIT MANUALLY. Re-run the script to regenerate.
// ═══════════════════════════════════════════════════════════════

"""

    full_output = header + output + "\n"

    if args.output:
        with open(args.output, "w") as f:
            f.write(full_output)
        print(f"Written to {args.output}")
    else:
        print(full_output)


if __name__ == "__main__":
    main()
